# Generated by Django 4.2.2 on 2023-06-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='referencia',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
